# Generated by Django 4.2.6 on 2023-11-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
