# Generated by Django 4.2.6 on 2023-11-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmodel',
            old_name='Book',
            new_name='book',
        ),
    ]
