# Generated by Django 4.2.6 on 2024-05-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_remove_bookmodel_saved_by_users'),
        ('add_to_cart', '0004_rename_book_orderdetailmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bookmodel'),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_to_cart.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
