# Generated by Django 4.2.6 on 2023-11-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customermodel_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='saved',
        ),
    ]
