# Generated by Django 4.2.6 on 2023-11-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_bookmodel_customer'),
        ('customer', '0004_customermodel_save_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='saved_books',
            field=models.ManyToManyField(blank=True, to='home.bookmodel'),
        ),
    ]
