# Generated by Django 4.2.6 on 2023-11-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customermodel_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='save_book',
            field=models.BooleanField(default=False),
        ),
    ]
