# Generated by Django 4.2.6 on 2023-11-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customermodel_saved_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='save_book',
        ),
    ]
