# Generated by Django 4.2.6 on 2024-05-17 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0004_chatmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
