# Generated by Django 4.2.6 on 2023-10-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookmodel_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
