# Generated by Django 4.2.6 on 2023-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookmodel_color_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='save_book',
            field=models.BooleanField(null=True),
        ),
    ]
