# Generated by Django 4.2.6 on 2023-11-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_bookmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='save_book',
        ),
    ]
