# Generated by Django 4.2.6 on 2023-11-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customermodel_saved'),
        ('home', '0023_remove_bookmodel_arthur_bookmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='save_book',
            field=models.BooleanField(default=False),
        ),
    ]
