# Generated by Django 4.2.6 on 2023-11-23 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_remove_bookmodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='saved_by_users',
            field=models.ManyToManyField(related_name='saved_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
