# Generated by Django 4.2.6 on 2024-05-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_bookmodel_saved_by_users'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bookmodel'),
        ),
    ]
