# Generated by Django 4.2.6 on 2023-10-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('quanlity_page', models.IntegerField()),
                ('arthur', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('birth', models.DateTimeField()),
            ],
        ),
    ]
