# Generated by Django 4.2.6 on 2023-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookmodel_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
