# Generated by Django 4.2.6 on 2023-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='link_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
