# Generated by Django 4.2.6 on 2023-10-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookmodel_link_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='quanlity_page',
            new_name='quantity_page',
        ),
    ]
