# Generated by Django 4.2.6 on 2023-10-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('home', '0006_rename_quanlity_page_bookmodel_quantity_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.categorybookmodel'),
        ),
    ]
