# Generated by Django 4.2.6 on 2023-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_bookmodel_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
