# Generated by Django 4.2.6 on 2023-11-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('home', '0011_bookmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category_name',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.categorybookmodel'),
        ),
    ]
