# Generated by Django 4.2.6 on 2023-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('home', '0012_remove_bookmodel_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category_name',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category_name',
            field=models.ManyToManyField(to='category.categorybookmodel'),
        ),
    ]
