# Generated by Django 4.2.6 on 2023-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_bookmodel_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='color_card',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
