# Generated by Django 4.2.6 on 2023-11-21 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_bookmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
