# Generated by Django 4.2.6 on 2023-11-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_bookmodel_save_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='arthur',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
